// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2g_Ue-OFLBNWD-YyrpRQlzrcd-sQJks',
    appId: '1:747268445695:web:d8e6ee60958b6d54b983ca',
    messagingSenderId: '747268445695',
    projectId: 'chat-app-project-22387',
    authDomain: 'chat-app-project-22387.firebaseapp.com',
    storageBucket: 'chat-app-project-22387.appspot.com',
    measurementId: 'G-1P2C63MZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19Ytn2aJaAWkpq1M2sefVf_W0XFfyvU0',
    appId: '1:747268445695:android:b6d71fac24da711db983ca',
    messagingSenderId: '747268445695',
    projectId: 'chat-app-project-22387',
    storageBucket: 'chat-app-project-22387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCwg6dEllgALpx4NwBJ_-rTD_jLGY4yI',
    appId: '1:747268445695:ios:a73a8586c3ba94afb983ca',
    messagingSenderId: '747268445695',
    projectId: 'chat-app-project-22387',
    storageBucket: 'chat-app-project-22387.appspot.com',
    iosBundleId: 'com.example.chatAppProject',
  );
}
